# ASL Ampersand Project
# Copyright (C) 2025, Bruce MacKinnon KC1FSZ
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# ( at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
cmake_minimum_required(VERSION 3.13)
set(CMAKE_C_STANDARD 17)
set(CMAKE_CXX_STANDARD 23)
project(amp-win C CXX ASM)

add_compile_options(-DCURL_STATICLIB -fstack-protector-all -Wall -Wpedantic -g)

# ----- Make resource objects ------------------------------------------------

# xxd -n _www_index_html -i ../amp-core/www/index.html resource-amp-core-www-index.c

# Converting an html file into a .c file. The temporary .c file is 
# created in the build directory.
set(RESOURCE0 "${CMAKE_CURRENT_SOURCE_DIR}/amp-core/www/index.html")
set(OBJECT0 "${CMAKE_CURRENT_BINARY_DIR}/resource-amp-core-www-index-html.c")
set(NAME0 "_amp_core_www_index_html")
add_custom_command(
    OUTPUT ${OBJECT0}
    COMMAND xxd
    ARGS 
        -n ${NAME0}
        -i 
        ${RESOURCE0}
        ${OBJECT0}
    DEPENDS ${RESOURCE0}
)

set(RESOURCE1 "${CMAKE_CURRENT_SOURCE_DIR}/amp-core/www/config.html")
set(OBJECT1 "${CMAKE_CURRENT_BINARY_DIR}/resource-amp-core-www-config-html.c")
set(NAME1 "_amp_core_www_config_html")
add_custom_command(
    OUTPUT ${OBJECT1}
    COMMAND xxd
    ARGS 
        -n ${NAME1}
        -i 
        ${RESOURCE1}
        ${OBJECT1}
    DEPENDS ${RESOURCE1}
)

set(RESOURCE2 "${CMAKE_CURRENT_SOURCE_DIR}/amp-core/www/main.css")
set(OBJECT2 "${CMAKE_CURRENT_BINARY_DIR}/resource-amp-core-www-main-css.c")
set(NAME2 "_amp_core_www_main_css")
add_custom_command(
    OUTPUT ${OBJECT2}
    COMMAND xxd
    ARGS 
        -n ${NAME2}
        -i 
        ${RESOURCE2}
        ${OBJECT2}
    DEPENDS ${RESOURCE2}
)

# In order to simplify distribution, the Windows binary incorporates the
# CA CERTS file as a static resources. This is downloaded from the CURL
# website, which is in turn refreshed from Mozilla.
# 
# See: https://curl.se/docs/caextract.html
# 
# What happens here is that we download the .pem file and then turn it 
# into a static C array using xxd.
#
# The array is called "curl_cacerts."
#
add_custom_command(OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/cacerts.h
  COMMAND wget https://curl.se/ca/cacert.pem -O ${CMAKE_CURRENT_BINARY_DIR}/cacerts.pem
  COMMAND xxd -n curl_cacerts -i ${CMAKE_CURRENT_BINARY_DIR}/cacerts.pem ${CMAKE_CURRENT_BINARY_DIR}/cacerts.h
  COMMENT "Fetching CACERTS"
  VERBATIM
)
add_custom_target(cacerts DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/cacerts.h)

# ----- The Web UI version ---------------------------------------------------

add_executable(amp-win
  src/main.cpp
  src/config-handler.cpp
  src/service-thread.cpp
  src/LineRadioWin.cpp
  amp-core/src/ConfigPoller.cpp
  amp-core/src/EventLoop.cpp
  amp-core/src/Message.cpp
  amp-core/src/Line.cpp
  amp-core/src/LineRadio.cpp
  amp-core/src/LineIAX2.cpp
  amp-core/src/LineParrot.cpp
  amp-core/src/IAX2FrameFull.cpp
  amp-core/src/IAX2Util.cpp
  amp-core/src/RegisterTask.cpp
  amp-core/src/StatsTask.cpp
  amp-core/src/Transcoder_G711_ULAW.cpp
  amp-core/src/Transcoder_SLIN_48K.cpp
  amp-core/src/Transcoder_SLIN_16K.cpp
  amp-core/src/Transcoder_SLIN_8K.cpp
  amp-core/src/Transcoder_G726.cpp
  amp-core/src/Bridge.cpp
  amp-core/src/BridgeCall.cpp
  amp-core/src/BridgeIn.cpp
  amp-core/src/BridgeOut.cpp
  amp-core/src/Resampler.cpp
  amp-core/src/WebUi.cpp
  amp-core/src/KerchunkFilter.cpp
  amp-core/src/MultiRouter.cpp
  amp-core/src/ThreadUtil.cpp
  amp-core/src/TraceLog.cpp
  amp-core/src/ProgramUtils.cpp
  kc1fsz-tools-cpp/src/Common.cpp
  kc1fsz-tools-cpp/src/NetUtils.cpp
  kc1fsz-tools-cpp/src/DTMFDetector2.cpp
  kc1fsz-tools-cpp/src/MicroDNS.cpp
  kc1fsz-tools-cpp/src/StdPollTimer.cpp
  kc1fsz-tools-cpp/src/fixed_math.cpp  
  kc1fsz-tools-cpp/src/linux/StdClock.cpp
  kc1fsz-tools-cpp/src/win32/Win32MTLog.cpp
  kc1fsz-tools-cpp/src/md5/md5c.c
  kc1fsz-tools-cpp/src/TaggedBuffer.cpp
  itu-g711-codec/src/codec.cpp
  itu-g711-codec/src/Plc.cpp
  cmsis-dsp-mock/src/main.cpp
  cmsis-dsp-mock/src/main-float.cpp
  kc1fsz-sdrc/sw/src/TestToneGenerator.cpp
  kc1fsz-sdrc/sw/src/IDToneGenerator.cpp
  kc1fsz-sdrc/sw/src/CourtesyToneGenerator.cpp
  kc1fsz-sdrc/sw/src/Tx.cpp
  kc1fsz-sdrc/sw/src/TxControl.cpp
  ed25519/src/add_scalar.c
  ed25519/src/ge.c
  ed25519/src/keypair.c
  ed25519/src/seed.c
  ed25519/src/sign.c
  ed25519/src/fe.c
  ed25519/src/key_exchange.c
  ed25519/src/sc.c
  ed25519/src/sha512.c
  ed25519/src/verify.c
  g726-codec/src/g711.c
  g726-codec/src/g72x.c
  g726-codec/src/g726_32.c
  base64.c/base64.c
  cacerts.h
# Here is where the resources are added to the binary
  ${OBJECT0}
  ${OBJECT1}
  ${OBJECT2}
)
add_dependencies(amp-win cacerts)

target_include_directories(amp-win PRIVATE src)
target_include_directories(amp-win PRIVATE include)
target_include_directories(amp-win PRIVATE kc1fsz-tools-cpp/include)
target_include_directories(amp-win PRIVATE itu-g711-codec/src)
target_include_directories(amp-win PRIVATE cmsis-dsp-mock/include)
target_include_directories(amp-win PRIVATE amp-core/src)
target_include_directories(amp-win PRIVATE amp-core/include)
target_include_directories(amp-win PRIVATE kc1fsz-sdrc/sw/include)
target_include_directories(amp-win PRIVATE kc1fsz-sdrc/sw/src)
target_include_directories(amp-win PRIVATE ed25519/src)
target_include_directories(amp-win PRIVATE json/include)
target_include_directories(amp-win PRIVATE cpp-httplib)
target_include_directories(amp-win PRIVATE argparse/include)
target_include_directories(amp-win PRIVATE g726-codec/src)
target_include_directories(amp-win PRIVATE base64.c)

# Needed for the cacert.h
target_include_directories(amp-win PRIVATE ${CMAKE_CURRENT_BINARY_DIR})

target_link_options(amp-win PRIVATE -static-libgcc -static-libstdc++)
# Needed to expand the size of the stack in the MinGW environment
target_link_options(amp-win PRIVATE -Wl,--stack,4096000)
target_link_libraries(amp-win -lws2_32 -lole32)
# Created using:  pkg-config.exe --libs --static libcurl
target_link_libraries(amp-win -static -lcurl -lssl -lcrypto -lz -lwldap32 -lws2_32 -liphlpapi -lbcrypt -ladvapi32 -lcrypt32 -lsecur32 -lssh2 -lws2_32 -lz -lbrotlidec -lbrotlicommon -lzstd -lnghttp2 -lngtcp2 -lngtcp2_crypto_ossl -L/lib -lssl -lcrypto -lws2_32 -lgdi32 -lcrypt32 -lnghttp3 -lpsl -lunistring -lws2_32 -liconv -lidn2 -liconv -lunistring)

# ----- hello-audio ----------------------------------------------------

add_executable(hello-audio EXCLUDE_FROM_ALL
  src/tests/hello-audio-1.cpp
)
target_include_directories(hello-audio PRIVATE src)
target_include_directories(hello-audio PRIVATE include)
target_include_directories(hello-audio PRIVATE kc1fsz-tools-cpp/include)
target_link_libraries(hello-audio -lws2_32 -lcurl -lwinmm)
target_link_options(hello-audio PRIVATE -mwindows)

# ----- hello-audio-2 ----------------------------------------------------

add_executable(hello-audio-2 EXCLUDE_FROM_ALL
  src/tests/hello-audio-2.cpp
  kc1fsz-tools-cpp/src/linux/StdClock.cpp
)
target_include_directories(hello-audio-2 PRIVATE src)
target_include_directories(hello-audio-2 PRIVATE include)
target_include_directories(hello-audio-2 PRIVATE kc1fsz-tools-cpp/include)
target_link_libraries(hello-audio-2 -lole32)
target_link_options(hello-audio-2 PRIVATE -mwindows)

# ----- hello-http-server -------------------------------------------------

add_executable(hello-http-server EXCLUDE_FROM_ALL
  src/demos/hello-http-server.cpp
  kc1fsz-tools-cpp/src/linux/StdClock.cpp
)
target_include_directories(hello-http-server PRIVATE src)
target_include_directories(hello-http-server PRIVATE include)
target_include_directories(hello-http-server PRIVATE kc1fsz-tools-cpp/include)
target_include_directories(hello-http-server PRIVATE cpp-httplib)
target_link_libraries(hello-http-server -lws2_32)
target_link_options(hello-http-server PRIVATE -mwindows)
